version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/react-tutorial
     - /react-tutorial/node_modules
    command: sh -c "npm start"
    ports:
     - "3000:3000"
